//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string Id { get; set; }
        public string PinCode { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
